# Generated by Django 3.2 on 2023-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
